const vipData = [{
  "level": 0,
  "integral": 500,
  "backgroundColor": "#9ea2ae",
  "backgroundImage": "v0bg.png",
  "privilege": [{
    "icon": "vip_icon_1.png",
    "name": "礼包福利特权",
    "type": 1
  }, {
    "icon": "vip_icon_2.png",
    "name": "新游体验特权",
    "type": 2
  }]
}, {
  "level": 1,
  "integral": 4000,
  "backgroundColor": "#3a424f",
  "backgroundImage": "v1-3bg.png",
  "privilege": [{
    "icon": "vip_icon_1.png",
    "name": "礼包福利特权",
    "type": 1
  }, {
    "icon": "vip_icon_2.png",
    "name": "新游体验特权",
    "type": 2
  }]
}, {
  "level": 2,
  "integral": 10000,
  "backgroundColor": "#3a424f",
  "backgroundImage": "v1-3bg.png",
  "privilege": [{
    "icon": "vip_icon_1.png",
    "name": "礼包福利特权",
    "type": 1
  }, {
    "icon": "vip_icon_2.png",
    "name": "新游体验特权",
    "type": 2
  }, {
    "icon": "vip_icon_3.png",
    "name": "生日卡券特权",
    "type": 3
  }, {
    "icon": "vip_icon_4.png",
    "name": "卡券福利特权",
    "type": 4
  }, {
    "icon": "vip_icon_5.png",
    "name": "短信安全特权",
    "type": 5
  }]
}, {
  "level": 3,
  "integral": 30000,
  "backgroundColor": "#3a424f",
  "backgroundImage": "v1-3bg.png",
  "privilege": [{
    "icon": "vip_icon_1.png",
    "name": "礼包福利特权",
    "type": 1
  }, {
    "icon": "vip_icon_2.png",
    "name": "新游体验特权",
    "type": 2
  }, {
    "icon": "vip_icon_3.png",
    "name": "生日卡券特权",
    "type": 3
  }, {
    "icon": "vip_icon_4.png",
    "name": "卡券福利特权",
    "type": 4
  }, {
    "icon": "vip_icon_5.png",
    "name": "短信安全特权",
    "type": 5
  }, {
    "icon": "vip_icon_6.png",
    "name": "炫彩昵称特权",
    "type": 6
  }, {
    "icon": "vip_icon_7.png",
    "name": "工单优先处理",
    "type": 7
  }]
}, {
  "level": 4,
  "integral": 100000,
  "backgroundColor": "#c09f69",
  "backgroundImage": "v4-6bg.png",
  "privilege": [{
    "icon": "vip_icon_1.png",
    "name": "礼包福利特权",
    "type": 1
  }, {
    "icon": "vip_icon_2.png",
    "name": "新游体验特权",
    "type": 2
  }, {
    "icon": "vip_icon_3.png",
    "name": "生日卡券特权",
    "type": 3
  }, {
    "icon": "vip_icon_4.png",
    "name": "卡券福利特权",
    "type": 4
  }, {
    "icon": "vip_icon_5.png",
    "name": "短信安全特权",
    "type": 5
  }, {
    "icon": "vip_icon_6.png",
    "name": "炫彩昵称特权",
    "type": 6
  }, {
    "icon": "vip_icon_7.png",
    "name": "工单优先处理",
    "type": 7
  }, {
    "icon": "vip_icon_8.png",
    "name": "提前通知特权",
    "type": 8
  }, {
    "icon": "vip_icon_9.png",
    "name": "客服优先特权",
    "type": 9
  }]
}, {
  "level": 5,
  "integral": 300000,
  "backgroundColor": "#c09f69",
  "backgroundImage": "v4-6bg.png",
  "privilege": [{
    "icon": "vip_icon_1.png",
    "name": "礼包福利特权",
    "type": 1
  }, {
    "icon": "vip_icon_2.png",
    "name": "新游体验特权",
    "type": 2
  }, {
    "icon": "vip_icon_3.png",
    "name": "生日卡券特权",
    "type": 3
  }, {
    "icon": "vip_icon_4.png",
    "name": "卡券福利特权",
    "type": 4
  }, {
    "icon": "vip_icon_5.png",
    "name": "短信安全特权",
    "type": 5
  }, {
    "icon": "vip_icon_6.png",
    "name": "炫彩昵称特权",
    "type": 6
  }, {
    "icon": "vip_icon_7.png",
    "name": "工单优先处理",
    "type": 7
  }, {
    "icon": "vip_icon_8.png",
    "name": "提前通知特权",
    "type": 8
  }, {
    "icon": "vip_icon_9.png",
    "name": "客服优先特权",
    "type": 9
  }, {
    "icon": "vip_icon_10.png",
    "name": "游戏总监预约",
    "type": 10
  }]
}, {
  "level": 6,
  "integral": 800000,
  "backgroundColor": "#c09f69",
  "backgroundImage": "v4-6bg.png",
  "privilege": [{
    "icon": "vip_icon_1.png",
    "name": "礼包福利特权",
    "type": 1
  }, {
    "icon": "vip_icon_2.png",
    "name": "新游体验特权",
    "type": 2
  }, {
    "icon": "vip_icon_3.png",
    "name": "生日卡券特权",
    "type": 3
  }, {
    "icon": "vip_icon_4.png",
    "name": "卡券福利特权",
    "type": 4
  }, {
    "icon": "vip_icon_5.png",
    "name": "短信安全特权",
    "type": 5
  }, {
    "icon": "vip_icon_6.png",
    "name": "炫彩昵称特权",
    "type": 6
  }, {
    "icon": "vip_icon_7.png",
    "name": "工单优先处理",
    "type": 7
  }, {
    "icon": "vip_icon_8.png",
    "name": "提前通知特权",
    "type": 8
  }, {
    "icon": "vip_icon_9.png",
    "name": "客服优先特权",
    "type": 9
  }, {
    "icon": "vip_icon_10.png",
    "name": "游戏总监预约",
    "type": 10
  }, {
    "icon": "vip_icon_11.png",
    "name": "区服命名特权",
    "type": 11
  }]
}, {
  "level": 7,
  "integral": 2000000,
  "backgroundColor": "#2e2e2e",
  "backgroundImage": "v7-9bg.png",
  "privilege": [{
    "icon": "vip_icon_1.png",
    "name": "礼包福利特权",
    "type": 1
  }, {
    "icon": "vip_icon_2.png",
    "name": "新游体验特权",
    "type": 2
  }, {
    "icon": "vip_icon_3.png",
    "name": "生日卡券特权",
    "type": 3
  }, {
    "icon": "vip_icon_4.png",
    "name": "卡券福利特权",
    "type": 4
  }, {
    "icon": "vip_icon_5.png",
    "name": "短信安全特权",
    "type": 5
  }, {
    "icon": "vip_icon_6.png",
    "name": "炫彩昵称特权",
    "type": 6
  }, {
    "icon": "vip_icon_7.png",
    "name": "工单优先处理",
    "type": 7
  }, {
    "icon": "vip_icon_8.png",
    "name": "提前通知特权",
    "type": 8
  }, {
    "icon": "vip_icon_9.png",
    "name": "客服优先特权",
    "type": 9
  }, {
    "icon": "vip_icon_10.png",
    "name": "游戏总监预约",
    "type": 10
  }, {
    "icon": "vip_icon_11.png",
    "name": "区服命名特权",
    "type": 11
  }, {
    "icon": "vip_icon_12.png",
    "name": "周边礼物赠送",
    "type": 12
  }]
}, {
  "level": 8,
  "integral": 5000000,
  "backgroundColor": "#2e2e2e",
  "backgroundImage": "v7-9bg.png",
  "privilege": [{
    "icon": "vip_icon_1.png",
    "name": "礼包福利特权",
    "type": 1
  }, {
    "icon": "vip_icon_2.png",
    "name": "新游体验特权",
    "type": 2
  }, {
    "icon": "vip_icon_3.png",
    "name": "生日卡券特权",
    "type": 3
  }, {
    "icon": "vip_icon_4.png",
    "name": "卡券福利特权",
    "type": 4
  }, {
    "icon": "vip_icon_5.png",
    "name": "短信安全特权",
    "type": 5
  }, {
    "icon": "vip_icon_6.png",
    "name": "炫彩昵称特权",
    "type": 6
  }, {
    "icon": "vip_icon_7.png",
    "name": "工单优先处理",
    "type": 7
  }, {
    "icon": "vip_icon_8.png",
    "name": "提前通知特权",
    "type": 8
  }, {
    "icon": "vip_icon_9.png",
    "name": "客服优先特权",
    "type": 9
  }, {
    "icon": "vip_icon_10.png",
    "name": "游戏总监预约",
    "type": 10
  }, {
    "icon": "vip_icon_11.png",
    "name": "区服命名特权",
    "type": 11
  }, {
    "icon": "vip_icon_12.png",
    "name": "周边礼物赠送",
    "type": 12
  }, {
    "icon": "vip_icon_13.png",
    "name": "装备被盗追回",
    "type": 13
  }]
}, {
  "level": 9,
  "integral": 'max',
  "backgroundColor": "#2e2e2e",
  "backgroundImage": "v7-9bg.png",
  "privilege": [{
    "icon": "vip_icon_1.png",
    "name": "礼包福利特权",
    "type": 1
  }, {
    "icon": "vip_icon_2.png",
    "name": "新游体验特权",
    "type": 2
  }, {
    "icon": "vip_icon_3.png",
    "name": "生日卡券特权",
    "type": 3
  }, {
    "icon": "vip_icon_4.png",
    "name": "卡券福利特权",
    "type": 4
  }, {
    "icon": "vip_icon_5.png",
    "name": "短信安全特权",
    "type": 5
  }, {
    "icon": "vip_icon_6.png",
    "name": "炫彩昵称特权",
    "type": 6
  }, {
    "icon": "vip_icon_7.png",
    "name": "工单优先处理",
    "type": 7
  }, {
    "icon": "vip_icon_8.png",
    "name": "提前通知特权",
    "type": 8
  }, {
    "icon": "vip_icon_9.png",
    "name": "客服优先特权",
    "type": 9
  }, {
    "icon": "vip_icon_10.png",
    "name": "游戏总监预约",
    "type": 10
  }, {
    "icon": "vip_icon_11.png",
    "name": "区服命名特权",
    "type": 11
  }, {
    "icon": "vip_icon_12.png",
    "name": "周边礼物赠送",
    "type": 12
  }, {
    "icon": "vip_icon_13.png",
    "name": "装备被盗追回",
    "type": 13
  }, {
    "icon": "vip_icon_14.png",
    "name": "安锋年会参与",
    "type": 14
  }]
}]

module.exports = vipData;